### PR TITLE
Start Readme.md information. Still Needed, unique in rails implementation?

### PR DESCRIPTION
**Pull request by MichaelDimmitt**
Still to be done,  

What are the Unique changes being brought into this implementation of Personal Dash?
If wanted, comment in the pull request and I can incorporate them into the readme.md

### CODE REVIEW

**Comment by MichaelDimmitt** [comment]
Benefits ryan has discussed of Rails Implementation :
1) After inputting credentials, allowing User Specific information.
2) @murjax figured out how make a dynamic time and weather box for my dashboard app.
3) There should be no issues refreshing and running ruby scripts to update information.

**Comment by murjax** [comment]
This version of Personal Dash is gonna display different, more generic and useful data than the old one. Data includes current time, weather, news, a link to a "how to" article, a quote of the day, and finally your local traffic. The traffic data will be dynamic based upon input locations. We need to update the readme to reflect this.

**Comment by MichaelDimmitt** [comment]
the initial commit, was a standard scaffold rails? or are is there additional code in the commit? Are we able to separate that logic out to make the project more readable?

**Comment by murjax** [comment]
The initial commit had some logic put in to get it working, but is mostly just the initial design I'm going for. As for logic, I'm going to be refactoring the views out into layouts and such. In other words I wouldn't take the existing code in the initial commit as the final result, but rather the base from which we are developing.

**Comment by MichaelDimmitt** [comment]
yeah, but do that in a future commit instead of rebasing back. Thanks.

**Comment by murjax** [comment]
Oh I don't plan on rebasing any of this anyway. History is history.

**Comment by m-dimmitt** [comment]
"link to how to article"
I need clarification,
is this a bunch of different how to articles?

want to try to add a "was last seen feature"? 🤣 
http://floridaelago.com/

or a recent notifications feature?
https://muzzleapp.com/

**Pull request merged**
